import { BaseEventManager } from "../../events/BaseEventManager";
import type { InGameManager } from "../InGameManager";
export declare class InGameEventManager extends BaseEventManager {
    private readonly inGameManager;
    private readonly blockExplode;
    private readonly buttonPush;
    private readonly dataDrivenEntityTrigger;
    private readonly effectAdd;
    private readonly entityDie;
    private readonly entityHealthChanged;
    private readonly entityHitBlock;
    private readonly entityHitEntity;
    private readonly entityHurt;
    private readonly entityLoad;
    private readonly entityRemove;
    private readonly entitySpawn;
    private readonly explosion;
    private readonly gameRuleChange;
    private readonly itemCompleteUse;
    private readonly itemReleaseUse;
    private readonly itemStartUse;
    private readonly itemStartUseOn;
    private readonly itemStopUse;
    private readonly itemStopUseOn;
    private readonly itemUse;
    private readonly leverAction;
    private readonly pistonActivate;
    private readonly playerBreakBlock;
    private readonly playerButtonInput;
    private readonly playerDimensionChange;
    private readonly playerEmote;
    private readonly playerGameModeChange;
    private readonly playerHotbarSelectedSlotChange;
    private readonly playerInputModeChange;
    private readonly playerInputPermissionCategoryChange;
    private readonly playerInteractWithBlock;
    private readonly playerInteractWithEntity;
    private readonly playerInventoryItemChange;
    private readonly playerJoin;
    private readonly playerLeave;
    private readonly playerPlaceBlock;
    private readonly playerSpawn;
    private readonly pressurePlatePop;
    private readonly pressurePlatePush;
    private readonly projectileHitBlock;
    private readonly projectileHitEntity;
    private readonly targetBlockHit;
    private readonly weatherChange;
    private constructor();
    static create(inGameManager: InGameManager): InGameEventManager;
    subscribeAll(): void;
    unsubscribeAll(): void;
    getInGameManager(): InGameManager;
}
